---
- hosts: all
  become: true

  tasks:

  - name: create a test file on both servers
    ansible.builtin.file:
      path: /etc/filetest.txt
      state: touch
      mode: '1777'

  - name: install apache2 package
    ansible.builtin.apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd package
    ansible.builtin.dnf5:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"
