---
- hosts: all
  become: true

  tasks:

  - name: create a test file on both servers
    ansible.builtin.file:
      path: /etc/filetest.txt
      state: touch
      mode: '1777'

  - name: install apache2 package
    ansible.builtin.package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
